### ISSUE TITLE
Poor performance on Sublime Text 4

### ISSUE THREAD

**Issue by ifaniqbal** [danklammer/tailwind-sublime-autocomplete#11]
The auto-complete pop up appear slower in ST4. I've tested it on both fresh install of ST3 and ST4 with only this package installed.

Do you think this an issue for the package or ST4?

**Comment by rjdusk** [comment]
I'm also experiencing the same issue. It's painfully slow, I've had to disable the package to make ST usable again.

**Comment by lukedanielson** [comment]
I am unable to get autocompletions to show up when file syntax is set to html in Sublime Text Version 4121. Is there something I'm doing wrong? For example, when typing `<body class="bg-` nothing comes up, and `ctrl+space` says `No available completions`

ST settings file here:

```json
{
    "theme": "Default Dark.sublime-theme",
    "color_scheme": "Packages/gruvbox/gruvbox (Dark) (Medium).sublime-color-scheme",
    "detect_indentation": true,
	"font_face": "Cascadia Code",
	"font_size": 16,
	"ignored_packages":[
		"Vintage"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"show_encoding": true,
	"tab_size": 4,
	"translate_tabs_to_spaces": true,
	"word_separators": "./\\()\"'-,.;<>~!@#$%^&*|+=[]{}`~?",
	"tab_completion": true,
	"auto_complete": true,
}
```

What am I missing? Thanks for the help?

**Comment by danklammer** [comment]
@lukedanielson Everything looks correct. Make sure you have your file saved (.html or whatever you are using).

As far as perf goes, I haven't had a problem. There looks to be a lot of perf enhancement in recent releases.

**Comment by hilarysk** [comment]
@lukedanielson, I'm using sublime 4126 and having the same problem. Did you ever get it working?
