### ISSUE TITLE
Tailwind 2.0 support

### ISSUE THREAD

**Issue by kevinvalk** [danklammer/tailwind-sublime-autocomplete#8]
Super useful plugin! I have switched to Tailwind 2.0 so I was wondering what are your plans for Tailwind 2.0 support?

https://blog.tailwindcss.com/tailwindcss-v2

Thanks

**Comment by n0ah01** [comment]
#9 I agree, great plugin.
Please double-check if my class-export was successfull, if yes than we should now have Tailwind v2 support for this beautifull plugin :)

**Comment by kevinvalk** [comment]
Great work to both of you and thanks 🥇
